### ISSUE TITLE
Your git repository website does not work.

### ISSUE THREAD

**Issue by JordyMoos** [NoRedInk/elm-json-decode-pipeline#1]
When you [go to your repository](https://github.com/NoRedInk/json-decode-pipeline) then right to the text "Use pipelines to build JSON Decoders in Elm.", there is a link that does not work.

When do you think that link will be fixed?

_(I'm not asking when elm 0.19 will be out, or maybe i do)_

**Comment by lukewestby** [comment]
it'll start to work once elm 0.19.0 is officially released. what you've encountered here is a planned rename of https://github.com/NoRedInk/elm-decode-pipeline to make the name a little bit more direct. you can still find the existing 0.18.0 package at that link!
