### ISSUE TITLE
Porting to bucklescript-tea

### ISSUE THREAD

**Issue by neochrome** [NoRedInk/elm-json-decode-pipeline#12]
Hi,
I think this library has a good approach to get around the limitations of the mapN functions in the regular Json.Decoder module. Would it be permitted under the current licensing to port the whole module or parts of the module to OCaml and include in the [bucklescript-tea](https://github.com/OvermindDL1/bucklescript-tea) project?

**Comment by rtfeldman** [comment]
Sure! Just make sure to follow the attribution guidelines of the BSD-3-Clause license:

https://opensource.org/licenses/BSD-3-Clause
