### ISSUE TITLE
import nullable in examples

### ISSUE THREAD

**Issue by nathanbraun** [NoRedInk/elm-json-decode-pipeline#7]
This is really minor, but seems like the example would be clearer if you also imported nullable from Json.Decode.  Saw it used later in the examples and was confused for a bit/had to go back to the packages to see where it came from.

Cheers!

**Comment by petemcfarlane** [comment]
I had the same issue! Also, I think the example result is wrong - shouldn't the nullable email field provide `Just "sam@example.com` or `Nothing`?
