### ISSUE TITLE
Corrupt binary when compiling inside Docker

### ISSUE THREAD

**Issue by sashaafm** [NoRedInk/elm-json-decode-pipeline#9]
Hello, I'm working on a project where I compile the Elm sources inside a Docker container. We're using `docker-compose` to launch the development container and we access the Elm sources via a volume mapping the host directory where the sources live to a directory inside the container.

Whenever we compile the project we receive this message from `elm-json-decode-pipeline`:

```
Success! Compiled 8 modules.
-- CORRUPT BINARY - /home/project/.elm/0.19.0/package/NoRedInk/elm-json-decode-pipeline/1.0.0/objs.dat

The binary data at
/home/project/.elm/0.19.0/package/NoRedInk/elm-json-decode-pipeline/1.0.0/objs.dat
is corrupt.

Elm caches build artifacts in the following directories:

    /home/project/.elm
    elm-stuff/

Maybe you recently installed a command line tool or editor plugin that messes
with them? They definitely should not be doing that, but you never know! So
maybe try deleting them? Everything will be rebuilt from scratch. This may help
reveal the corrupting influence.
```

I've got no idea why this is happening. I'll leave the overall setup below:

- Host OS: Mac OS Mojave 10.14.3
- Docker for Mac 2.0.2.1
- Container Image: Elixir 1.8
- Elm: 0.19 (binary from GitHub release)

If you need any further info please let me know.

Thanks!

**Comment by michaelglass** [comment]
I'd suggest you kill your docker image cache.

This is likely an elm compiler error, please open an issue https://github.com/elm/compiler/
